"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useSession } from "next-auth/react";
import { motion } from "framer-motion";
import {
  Activity, Download, Loader2, AlertCircle, CheckCircle2, Code2,
  Sparkles, KeyRound, Gauge, BookOpen,
} from "lucide-react";
import Link from "next/link";
import {
  AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend,
} from "recharts";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

type Summary = {
  requests: { today: number; last7d: number; last30d: number; total: number };
  successRate: number;
  errorCount: number;
  avgLatencyMs: number | null;
  decks: { last30d: number; total: number };
  keys: { active: number; expiringSoon: number };
};

type TimeseriesPoint = { date: string; success: number; error: number };

type ApiDeck = {
  deckId: string;
  name: string;
  prompt: string;
  source: string;
  numSlides: number;
  engine: string | null;
  status: string;
  audienceType: string;
  createdAt: string;
  presentationId: string | null;
  version: number | null;
  downloadUrl: string | null;
  apiKeyId: string | null;
};

type ApiRequest = {
  id: string;
  method: string;
  endpoint: string;
  statusCode: number;
  latencyMs: number;
  jobId: string | null;
  errorCode: string | null;
  ip: string | null;
  keyId: string | null;
  keyName: string | null;
  keyLast4: string | null;
  createdAt: string;
};

const ease = [0.22, 1, 0.36, 1] as const;

export default function ApiUsagePage() {
  useSession({ required: true });

  const [days, setDays] = useState(30);
  const [statusFilter, setStatusFilter] = useState<"all" | "success" | "error">("all");
  const [sourceFilter, setSourceFilter] = useState<"all" | "api" | "mcp">("all");

  const { data: summary, isLoading: loadingSummary } = useQuery<Summary>({
    queryKey: ["api-usage-summary"],
    queryFn: async () => {
      const r = await fetch("/api/user/api-usage/summary");
      if (!r.ok) throw new Error("Failed to load");
      return r.json();
    },
  });

  const { data: timeseries } = useQuery<{ points: TimeseriesPoint[] }>({
    queryKey: ["api-usage-timeseries", days],
    queryFn: async () => {
      const r = await fetch(`/api/user/api-usage/timeseries?days=${days}`);
      if (!r.ok) throw new Error("Failed to load");
      return r.json();
    },
  });

  const { data: decksPage, isLoading: loadingDecks } = useQuery<{ items: ApiDeck[] }>({
    queryKey: ["api-usage-decks", sourceFilter],
    queryFn: async () => {
      const r = await fetch(`/api/user/api-usage/decks?source=${sourceFilter}&limit=50`);
      if (!r.ok) throw new Error("Failed to load");
      return r.json();
    },
  });

  const { data: requestsPage, isLoading: loadingRequests } = useQuery<{ items: ApiRequest[] }>({
    queryKey: ["api-usage-requests", statusFilter],
    queryFn: async () => {
      const r = await fetch(`/api/user/api-usage/requests?status=${statusFilter}&limit=50`);
      if (!r.ok) throw new Error("Failed to load");
      return r.json();
    },
  });

  return (
    <div className="min-h-screen flex bg-background">
      <AppSidebar />
      <main className="flex-1 ml-[72px]">
        <div className="max-w-6xl mx-auto px-6 py-8 space-y-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease }}
          >
            <div className="flex items-end justify-between gap-4 flex-wrap">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <Activity className="h-4 w-4 text-primary" />
                  <h1 className="text-xl font-semibold tracking-tight">API Usage &amp; Monitoring</h1>
                </div>
                <p className="text-sm text-muted-foreground">
                  Decks generated by the REST API and MCP server, plus a live view of every request your keys have made.
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Link href="/docs">
                  <Button size="sm" variant="outline" className="h-8 text-xs gap-1.5">
                    <BookOpen className="h-3.5 w-3.5" />
                    Docs
                  </Button>
                </Link>
                <Link href="/settings">
                  <Button size="sm" variant="outline" className="h-8 text-xs gap-1.5">
                    <KeyRound className="h-3.5 w-3.5" />
                    Manage keys
                  </Button>
                </Link>
              </div>
            </div>
          </motion.div>

          {/* KPI cards */}
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.05, duration: 0.4, ease }}
            className="grid grid-cols-2 lg:grid-cols-4 gap-3"
          >
            <KpiCard
              label="Requests · 24h"
              value={summary?.requests.today ?? 0}
              loading={loadingSummary}
            />
            <KpiCard
              label="Requests · 30d"
              value={summary?.requests.last30d ?? 0}
              loading={loadingSummary}
              hint={`${summary?.requests.last7d ?? 0} in last 7 days`}
            />
            <KpiCard
              label="Success rate · 30d"
              value={summary ? `${(summary.successRate * 100).toFixed(1)}%` : "—"}
              loading={loadingSummary}
              hint={summary && summary.errorCount > 0 ? `${summary.errorCount} errors` : "no errors"}
              tone={summary ? (summary.successRate >= 0.99 ? "ok" : summary.successRate >= 0.9 ? "warn" : "bad") : "neutral"}
            />
            <KpiCard
              label="Avg latency · 30d"
              value={summary?.avgLatencyMs ? `${summary.avgLatencyMs} ms` : "—"}
              loading={loadingSummary}
              icon={<Gauge className="h-3.5 w-3.5" />}
            />
          </motion.div>

          {/* Chart */}
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.4, ease }}
            className="rounded-xl border border-border bg-card p-4"
          >
            <div className="flex items-center justify-between mb-3">
              <div>
                <h2 className="text-sm font-semibold">Requests over time</h2>
                <p className="text-[11px] text-muted-foreground">Success vs. error counts per day.</p>
              </div>
              <div className="flex gap-1">
                {[7, 30, 90].map((n) => (
                  <button
                    key={n}
                    onClick={() => setDays(n)}
                    className={`text-[11px] px-2 py-1 rounded transition-colors ${
                      days === n
                        ? "bg-primary text-primary-foreground"
                        : "bg-secondary/40 text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {n}d
                  </button>
                ))}
              </div>
            </div>
            <div className="h-[220px]">
              {timeseries && timeseries.points.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={timeseries.points} margin={{ top: 5, right: 8, left: -10, bottom: 0 }}>
                    <defs>
                      <linearGradient id="ok" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={0.4} />
                        <stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0} />
                      </linearGradient>
                      <linearGradient id="err" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#f43f5e" stopOpacity={0.4} />
                        <stop offset="100%" stopColor="#f43f5e" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" opacity={0.15} />
                    <XAxis
                      dataKey="date"
                      tickFormatter={(d) => new Date(d).toLocaleDateString(undefined, { month: "short", day: "numeric" })}
                      tick={{ fontSize: 10 }}
                    />
                    <YAxis tick={{ fontSize: 10 }} />
                    <Tooltip
                      contentStyle={{ fontSize: 11, borderRadius: 6, border: "1px solid hsl(var(--border))", background: "hsl(var(--card))" }}
                      labelFormatter={(d) => new Date(d as string).toLocaleDateString()}
                    />
                    <Legend wrapperStyle={{ fontSize: 11 }} />
                    <Area type="monotone" dataKey="success" stroke="hsl(var(--primary))" fill="url(#ok)" />
                    <Area type="monotone" dataKey="error" stroke="#f43f5e" fill="url(#err)" />
                  </AreaChart>
                </ResponsiveContainer>
              ) : (
                <div className="h-full grid place-items-center text-xs text-muted-foreground">
                  {timeseries ? "No requests yet" : <Loader2 className="h-4 w-4 animate-spin" />}
                </div>
              )}
            </div>
          </motion.div>

          {/* API-generated decks table */}
          <motion.section
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.15, duration: 0.4, ease }}
          >
            <div className="flex items-center justify-between mb-3">
              <div>
                <h2 className="text-sm font-semibold flex items-center gap-2">
                  <Sparkles className="h-3.5 w-3.5 text-primary" />
                  Decks generated via API
                </h2>
                <p className="text-[11px] text-muted-foreground">
                  Read-only — download as PPTX. These decks do not appear on the main projects page.
                </p>
              </div>
              <div className="flex gap-1">
                {(["all", "api", "mcp"] as const).map((s) => (
                  <button
                    key={s}
                    onClick={() => setSourceFilter(s)}
                    className={`text-[11px] px-2.5 py-1 rounded transition-colors ${
                      sourceFilter === s
                        ? "bg-primary text-primary-foreground"
                        : "bg-secondary/40 text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {s === "all" ? "All" : s.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>
            <div className="rounded-xl border border-border bg-card overflow-hidden">
              {loadingDecks ? (
                <div className="px-5 py-12 flex justify-center">
                  <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                </div>
              ) : !decksPage?.items.length ? (
                <EmptyTable
                  icon={<Sparkles className="h-5 w-5" />}
                  title="No API-generated decks yet"
                  body="Call POST /api/v1/decks with one of your keys and the deck will appear here."
                />
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/40 text-[10px] uppercase tracking-wide text-muted-foreground">
                      <tr>
                        <Th>Deck</Th>
                        <Th>Source</Th>
                        <Th>Engine</Th>
                        <Th>Slides</Th>
                        <Th>Status</Th>
                        <Th>Created</Th>
                        <Th className="text-right">Download</Th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border/40">
                      {decksPage.items.map((d) => (
                        <tr key={d.deckId} className="hover:bg-muted/20">
                          <Td>
                            <div className="font-medium text-sm truncate max-w-[260px]" title={d.name}>{d.name}</div>
                            <div className="text-[10px] text-muted-foreground truncate max-w-[260px]" title={d.prompt}>
                              {d.prompt}
                            </div>
                          </Td>
                          <Td>
                            <Badge variant="outline" className="text-[9px] h-4 px-1.5 uppercase">{d.source}</Badge>
                          </Td>
                          <Td className="text-[11px] text-muted-foreground">{d.engine || "—"}</Td>
                          <Td className="text-xs">{d.numSlides}</Td>
                          <Td>
                            <StatusPill status={d.status} />
                          </Td>
                          <Td className="text-[11px] text-muted-foreground whitespace-nowrap">
                            {new Date(d.createdAt).toLocaleString()}
                          </Td>
                          <Td className="text-right">
                            {d.downloadUrl ? (
                              <a
                                href={d.downloadUrl}
                                target="_blank"
                                rel="noreferrer noopener"
                                className="inline-flex items-center gap-1 text-[11px] text-primary hover:underline"
                              >
                                <Download className="h-3 w-3" />
                                .pptx
                              </a>
                            ) : (
                              <span className="text-[11px] text-muted-foreground/50">—</span>
                            )}
                          </Td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </motion.section>

          {/* Requests table */}
          <motion.section
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.4, ease }}
          >
            <div className="flex items-center justify-between mb-3">
              <div>
                <h2 className="text-sm font-semibold flex items-center gap-2">
                  <Code2 className="h-3.5 w-3.5 text-primary" />
                  Recent API requests
                </h2>
                <p className="text-[11px] text-muted-foreground">
                  Full audit trail. Status code, latency, and error reason for every request your keys made.
                </p>
              </div>
              <div className="flex gap-1">
                {(["all", "success", "error"] as const).map((s) => (
                  <button
                    key={s}
                    onClick={() => setStatusFilter(s)}
                    className={`text-[11px] px-2.5 py-1 rounded transition-colors capitalize ${
                      statusFilter === s
                        ? "bg-primary text-primary-foreground"
                        : "bg-secondary/40 text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
            <div className="rounded-xl border border-border bg-card overflow-hidden">
              {loadingRequests ? (
                <div className="px-5 py-12 flex justify-center">
                  <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                </div>
              ) : !requestsPage?.items.length ? (
                <EmptyTable
                  icon={<Code2 className="h-5 w-5" />}
                  title="No requests yet"
                  body="Once you call the API, every request lands here for you to audit."
                />
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-muted/40 text-[10px] uppercase tracking-wide text-muted-foreground">
                      <tr>
                        <Th>When</Th>
                        <Th>Endpoint</Th>
                        <Th>Status</Th>
                        <Th>Latency</Th>
                        <Th>Key</Th>
                        <Th>Error</Th>
                        <Th>Job</Th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border/40">
                      {requestsPage.items.map((r) => (
                        <tr key={r.id} className="hover:bg-muted/20">
                          <Td className="text-[11px] text-muted-foreground whitespace-nowrap">
                            {new Date(r.createdAt).toLocaleString()}
                          </Td>
                          <Td>
                            <span className="font-mono text-[11px]">
                              <span className="text-muted-foreground">{r.method}</span> {r.endpoint}
                            </span>
                          </Td>
                          <Td>
                            <StatusBadge code={r.statusCode} />
                          </Td>
                          <Td className="text-[11px] tabular-nums">{r.latencyMs}ms</Td>
                          <Td className="text-[11px]">
                            {r.keyName ? (
                              <span className="text-foreground">
                                {r.keyName}{" "}
                                <span className="font-mono text-muted-foreground/70">···{r.keyLast4}</span>
                              </span>
                            ) : (
                              <span className="text-muted-foreground/50">—</span>
                            )}
                          </Td>
                          <Td className="text-[11px]">
                            {r.errorCode ? (
                              <span className="text-rose-500 font-mono">{r.errorCode}</span>
                            ) : (
                              <span className="text-muted-foreground/50">—</span>
                            )}
                          </Td>
                          <Td className="text-[11px] font-mono text-muted-foreground/80">
                            {r.jobId ? (
                              <span title={r.jobId}>{r.jobId.slice(-8)}</span>
                            ) : (
                              <span className="text-muted-foreground/50">—</span>
                            )}
                          </Td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </motion.section>
        </div>
      </main>
    </div>
  );
}

// ─── Small UI helpers ───

function KpiCard({
  label,
  value,
  hint,
  loading,
  icon,
  tone = "neutral",
}: {
  label: string;
  value: number | string;
  hint?: string;
  loading?: boolean;
  icon?: React.ReactNode;
  tone?: "ok" | "warn" | "bad" | "neutral";
}) {
  const toneClass =
    tone === "ok" ? "text-emerald-500" :
    tone === "warn" ? "text-amber-500" :
    tone === "bad" ? "text-rose-500" :
    "text-foreground";
  return (
    <div className="rounded-xl border border-border bg-card px-4 py-3">
      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wide text-muted-foreground">
        {icon}
        {label}
      </div>
      <div className={`text-2xl font-semibold tabular-nums mt-1 ${toneClass}`}>
        {loading ? <Loader2 className="h-4 w-4 animate-spin opacity-50" /> : value}
      </div>
      {hint && <div className="text-[10px] text-muted-foreground mt-0.5">{hint}</div>}
    </div>
  );
}

function StatusPill({ status }: { status: string }) {
  const map: Record<string, { tone: "ok" | "warn" | "bad" | "neutral"; label: string }> = {
    COMPLETED: { tone: "ok", label: "Completed" },
    PROCESSING: { tone: "warn", label: "Processing" },
    FAILED: { tone: "bad", label: "Failed" },
    QUEUED: { tone: "neutral", label: "Queued" },
    UNKNOWN: { tone: "neutral", label: "Unknown" },
  };
  const cfg = map[status.toUpperCase()] || { tone: "neutral" as const, label: status };
  const cls =
    cfg.tone === "ok" ? "bg-emerald-500/10 text-emerald-500" :
    cfg.tone === "warn" ? "bg-amber-500/10 text-amber-500" :
    cfg.tone === "bad" ? "bg-rose-500/10 text-rose-500" :
    "bg-secondary/50 text-muted-foreground";
  return <span className={`text-[10px] px-1.5 py-0.5 rounded ${cls}`}>{cfg.label}</span>;
}

function StatusBadge({ code }: { code: number }) {
  const ok = code < 400;
  const cls = ok ? "bg-emerald-500/10 text-emerald-500" : code < 500 ? "bg-amber-500/10 text-amber-500" : "bg-rose-500/10 text-rose-500";
  return (
    <span className={`inline-flex items-center gap-1 text-[11px] font-mono px-1.5 py-0.5 rounded ${cls}`}>
      {ok ? <CheckCircle2 className="h-3 w-3" /> : <AlertCircle className="h-3 w-3" />}
      {code}
    </span>
  );
}

function Th({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <th className={`text-left px-3 py-2 font-medium ${className}`}>{children}</th>;
}

function Td({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-3 py-2.5 align-top ${className}`}>{children}</td>;
}

function EmptyTable({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="px-5 py-12 text-center">
      <div className="text-muted-foreground/40 mx-auto mb-2 flex justify-center">{icon}</div>
      <p className="text-sm font-medium">{title}</p>
      <p className="text-[11px] text-muted-foreground mt-1 max-w-md mx-auto">{body}</p>
    </div>
  );
}
