server {
    listen 80;
    server_name localhost;

    # Static files
    location ^~ /browser {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # WOPI discovery
    location ^~ /hosting/discovery {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # Capabilities
    location ^~ /hosting/capabilities {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # Main websocket
    location ~ ^/cool/(.*)/ws$ {
        proxy_pass http://collabora:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }

    # Admin websocket
    location ^~ /cool/adminws {
        proxy_pass http://collabora:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }

    # Download, presentation and image upload
    location ~ ^/(c|l)ool {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
    }

    # Cool proxy
    location ^~ /cool {
        proxy_pass http://collabora:9980;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 36000s;
    }
}
