// ISO 3166-1 alpha-2 → { numeric (alpha-3 numeric), name }
// Lookup used by the Visa world map (which joins on numeric codes).
// Covers the ~150 countries that account for essentially all real
// SaaS traffic. Missing entries are silently skipped on the map.

export const ISO_ALPHA2_TO_COUNTRY: Record<string, { numeric: string; name: string }> = {
  AD: { numeric: "020", name: "Andorra" },
  AE: { numeric: "784", name: "United Arab Emirates" },
  AF: { numeric: "004", name: "Afghanistan" },
  AG: { numeric: "028", name: "Antigua and Barbuda" },
  AL: { numeric: "008", name: "Albania" },
  AM: { numeric: "051", name: "Armenia" },
  AO: { numeric: "024", name: "Angola" },
  AR: { numeric: "032", name: "Argentina" },
  AT: { numeric: "040", name: "Austria" },
  AU: { numeric: "036", name: "Australia" },
  AZ: { numeric: "031", name: "Azerbaijan" },
  BA: { numeric: "070", name: "Bosnia and Herzegovina" },
  BB: { numeric: "052", name: "Barbados" },
  BD: { numeric: "050", name: "Bangladesh" },
  BE: { numeric: "056", name: "Belgium" },
  BF: { numeric: "854", name: "Burkina Faso" },
  BG: { numeric: "100", name: "Bulgaria" },
  BH: { numeric: "048", name: "Bahrain" },
  BI: { numeric: "108", name: "Burundi" },
  BJ: { numeric: "204", name: "Benin" },
  BN: { numeric: "096", name: "Brunei" },
  BO: { numeric: "068", name: "Bolivia" },
  BR: { numeric: "076", name: "Brazil" },
  BS: { numeric: "044", name: "Bahamas" },
  BT: { numeric: "064", name: "Bhutan" },
  BW: { numeric: "072", name: "Botswana" },
  BY: { numeric: "112", name: "Belarus" },
  BZ: { numeric: "084", name: "Belize" },
  CA: { numeric: "124", name: "Canada" },
  CD: { numeric: "180", name: "DR Congo" },
  CF: { numeric: "140", name: "Central African Republic" },
  CG: { numeric: "178", name: "Congo" },
  CH: { numeric: "756", name: "Switzerland" },
  CI: { numeric: "384", name: "Côte d'Ivoire" },
  CL: { numeric: "152", name: "Chile" },
  CM: { numeric: "120", name: "Cameroon" },
  CN: { numeric: "156", name: "China" },
  CO: { numeric: "170", name: "Colombia" },
  CR: { numeric: "188", name: "Costa Rica" },
  CU: { numeric: "192", name: "Cuba" },
  CV: { numeric: "132", name: "Cabo Verde" },
  CY: { numeric: "196", name: "Cyprus" },
  CZ: { numeric: "203", name: "Czechia" },
  DE: { numeric: "276", name: "Germany" },
  DJ: { numeric: "262", name: "Djibouti" },
  DK: { numeric: "208", name: "Denmark" },
  DO: { numeric: "214", name: "Dominican Republic" },
  DZ: { numeric: "012", name: "Algeria" },
  EC: { numeric: "218", name: "Ecuador" },
  EE: { numeric: "233", name: "Estonia" },
  EG: { numeric: "818", name: "Egypt" },
  ER: { numeric: "232", name: "Eritrea" },
  ES: { numeric: "724", name: "Spain" },
  ET: { numeric: "231", name: "Ethiopia" },
  FI: { numeric: "246", name: "Finland" },
  FJ: { numeric: "242", name: "Fiji" },
  FR: { numeric: "250", name: "France" },
  GA: { numeric: "266", name: "Gabon" },
  GB: { numeric: "826", name: "United Kingdom" },
  GE: { numeric: "268", name: "Georgia" },
  GH: { numeric: "288", name: "Ghana" },
  GM: { numeric: "270", name: "Gambia" },
  GN: { numeric: "324", name: "Guinea" },
  GR: { numeric: "300", name: "Greece" },
  GT: { numeric: "320", name: "Guatemala" },
  GY: { numeric: "328", name: "Guyana" },
  HK: { numeric: "344", name: "Hong Kong" },
  HN: { numeric: "340", name: "Honduras" },
  HR: { numeric: "191", name: "Croatia" },
  HT: { numeric: "332", name: "Haiti" },
  HU: { numeric: "348", name: "Hungary" },
  ID: { numeric: "360", name: "Indonesia" },
  IE: { numeric: "372", name: "Ireland" },
  IL: { numeric: "376", name: "Israel" },
  IN: { numeric: "356", name: "India" },
  IQ: { numeric: "368", name: "Iraq" },
  IR: { numeric: "364", name: "Iran" },
  IS: { numeric: "352", name: "Iceland" },
  IT: { numeric: "380", name: "Italy" },
  JM: { numeric: "388", name: "Jamaica" },
  JO: { numeric: "400", name: "Jordan" },
  JP: { numeric: "392", name: "Japan" },
  KE: { numeric: "404", name: "Kenya" },
  KG: { numeric: "417", name: "Kyrgyzstan" },
  KH: { numeric: "116", name: "Cambodia" },
  KR: { numeric: "410", name: "South Korea" },
  KW: { numeric: "414", name: "Kuwait" },
  KZ: { numeric: "398", name: "Kazakhstan" },
  LA: { numeric: "418", name: "Laos" },
  LB: { numeric: "422", name: "Lebanon" },
  LK: { numeric: "144", name: "Sri Lanka" },
  LT: { numeric: "440", name: "Lithuania" },
  LU: { numeric: "442", name: "Luxembourg" },
  LV: { numeric: "428", name: "Latvia" },
  LY: { numeric: "434", name: "Libya" },
  MA: { numeric: "504", name: "Morocco" },
  MD: { numeric: "498", name: "Moldova" },
  ME: { numeric: "499", name: "Montenegro" },
  MG: { numeric: "450", name: "Madagascar" },
  MK: { numeric: "807", name: "North Macedonia" },
  ML: { numeric: "466", name: "Mali" },
  MM: { numeric: "104", name: "Myanmar" },
  MN: { numeric: "496", name: "Mongolia" },
  MO: { numeric: "446", name: "Macao" },
  MR: { numeric: "478", name: "Mauritania" },
  MT: { numeric: "470", name: "Malta" },
  MU: { numeric: "480", name: "Mauritius" },
  MV: { numeric: "462", name: "Maldives" },
  MW: { numeric: "454", name: "Malawi" },
  MX: { numeric: "484", name: "Mexico" },
  MY: { numeric: "458", name: "Malaysia" },
  MZ: { numeric: "508", name: "Mozambique" },
  NA: { numeric: "516", name: "Namibia" },
  NE: { numeric: "562", name: "Niger" },
  NG: { numeric: "566", name: "Nigeria" },
  NI: { numeric: "558", name: "Nicaragua" },
  NL: { numeric: "528", name: "Netherlands" },
  NO: { numeric: "578", name: "Norway" },
  NP: { numeric: "524", name: "Nepal" },
  NZ: { numeric: "554", name: "New Zealand" },
  OM: { numeric: "512", name: "Oman" },
  PA: { numeric: "591", name: "Panama" },
  PE: { numeric: "604", name: "Peru" },
  PH: { numeric: "608", name: "Philippines" },
  PK: { numeric: "586", name: "Pakistan" },
  PL: { numeric: "616", name: "Poland" },
  PR: { numeric: "630", name: "Puerto Rico" },
  PS: { numeric: "275", name: "Palestine" },
  PT: { numeric: "620", name: "Portugal" },
  PY: { numeric: "600", name: "Paraguay" },
  QA: { numeric: "634", name: "Qatar" },
  RO: { numeric: "642", name: "Romania" },
  RS: { numeric: "688", name: "Serbia" },
  RU: { numeric: "643", name: "Russia" },
  RW: { numeric: "646", name: "Rwanda" },
  SA: { numeric: "682", name: "Saudi Arabia" },
  SD: { numeric: "729", name: "Sudan" },
  SE: { numeric: "752", name: "Sweden" },
  SG: { numeric: "702", name: "Singapore" },
  SI: { numeric: "705", name: "Slovenia" },
  SK: { numeric: "703", name: "Slovakia" },
  SL: { numeric: "694", name: "Sierra Leone" },
  SN: { numeric: "686", name: "Senegal" },
  SO: { numeric: "706", name: "Somalia" },
  SR: { numeric: "740", name: "Suriname" },
  SS: { numeric: "728", name: "South Sudan" },
  SV: { numeric: "222", name: "El Salvador" },
  SY: { numeric: "760", name: "Syria" },
  SZ: { numeric: "748", name: "Eswatini" },
  TD: { numeric: "148", name: "Chad" },
  TG: { numeric: "768", name: "Togo" },
  TH: { numeric: "764", name: "Thailand" },
  TJ: { numeric: "762", name: "Tajikistan" },
  TM: { numeric: "795", name: "Turkmenistan" },
  TN: { numeric: "788", name: "Tunisia" },
  TR: { numeric: "792", name: "Turkey" },
  TT: { numeric: "780", name: "Trinidad and Tobago" },
  TW: { numeric: "158", name: "Taiwan" },
  TZ: { numeric: "834", name: "Tanzania" },
  UA: { numeric: "804", name: "Ukraine" },
  UG: { numeric: "800", name: "Uganda" },
  US: { numeric: "840", name: "United States" },
  UY: { numeric: "858", name: "Uruguay" },
  UZ: { numeric: "860", name: "Uzbekistan" },
  VE: { numeric: "862", name: "Venezuela" },
  VN: { numeric: "704", name: "Vietnam" },
  YE: { numeric: "887", name: "Yemen" },
  ZA: { numeric: "710", name: "South Africa" },
  ZM: { numeric: "894", name: "Zambia" },
  ZW: { numeric: "716", name: "Zimbabwe" },
};

export function alpha2ToCountry(code: string | null | undefined) {
  if (!code) return null;
  return ISO_ALPHA2_TO_COUNTRY[code.toUpperCase()] || null;
}
